Fizzbuzz refactor 1 3
tsuruchan56/fizzbuzz-ynwa2021 pull request #3
Opened 2021-01-15 01:02 UTC by tsuruchan56

### 変更点
- READMEファイルを活用
   - プログラムについて(経緯と内容)
   - 課題の制約
   - 環境設定内容
   - 実行方法
   - テスト実行方法
   - 関連/特記事項

- UnitTestにおけるitの命名
　→何を期待しているのか、で命名。

- 各種関数名
　→何をする関数なのか、で命名。

- gitignoreファイル => coverageをコメントイン。
　→一部pushされてしまいました...

- `tofizzbuzz`（`chengeFizzBuzz`に変更）=>result変数を定義せずにreturnで戻り値として返す。
　→余計な変数定義は極力しない。

- if構文の整理
　→より厳密に比較できる(型)「===」に変更しました。
　→elseを削除しました。

- let => constに変更
　→再代入する予定が無い変数はconstで定義しました。

- sleceメソッド => 出力を配列に格納し、joinメソッドでカンマ区切りを実現。
　→sleceで余分なものを削除するよりもスマートなやり方だと思い変更しました。

- fizzbuzzへの変換ができているかのテストを倍数ごとに分けて実行
　→if構文の一つ一つをテストするという意図でテストを4つに分けました。

2021-01-15 01:28 UTC, tsuruchan56 commented on .gitignore
> -# coverage
`coverarge`
この部分、末尾に" / "が足りていなかったことが理由かなと仮説立てたのですがいかがでしょうか👀

2021-01-15 06:28 UTC, izumix03 requested changes
[1-3:改善方針]
・READMEファイルを活用して、「誰が見てもわかる」解説書を作ってみましょう！
  ・プログラムについての説明
  ・環境構築方法
  ・プログラム実行方法
 →内容OK！
 →書き方少しコメントします
 
・UnitTestにおけるitの命名について、「どんな期待値か」をより具体的にしてみましょう！
→OK

・.gitignoreを有効活用し、不要なファイルをGitに含めないようにしてみましょう！
→NG

・`tofizzbuzz`について
  ・`result`は必要でしょうか？よりシンプルに書けないか再考してみましょう！
  →OK

  ・比較演算子「==」を使うよりも適した比較方法はないでしょうか？
→OK

・各種関数名について、より適切な関数名はないか考えてみましょう！

・`let`を使うよりも適した変数定義はないでしょうか？
→OK

・`slice`を使わずに、配列をうまく利用することで実現できないか考えてみましょう！
→OK

・最後に、どんな意図でRefactorを行ったか、PR提出時にGithub上でコメント記載してみましょう！
→OK！もっと書いて良いので、ぜひ何考えたか沢山コメントして下さい。

2021-01-15 06:28 UTC, izumix03 commented on .gitignore
> -# coverage
回答になっていなければ申し訳ありません。

`# coverage` だとコメントアウトされていることになりますので、
動かなかったとしたらその影響かと思います。

2021-01-15 06:28 UTC, izumix03 commented on coverage/clover.xml
> +<coverage generated="1610607050382" clover="3.2.0">
[MUST]
一度pushされている状態のようなので、
`gitignore push 済み` のようなキーワードで検索してpushした coverage以下のファイルを取り消してみましょう！

2021-01-15 06:28 UTC, izumix03 commented on __tests__/index.test.ts
> +describe('return_value_matches_fizzbuzz', () => {
💯 
英語的な正しさは判断できませんが、何をしようとしているかわかりやすいコメントで素晴らしいと思います:sparkles:

2021-01-15 06:28 UTC, izumix03 commented on src/index.ts
> +export const chengeFizzBuzz = (number: number): string => {
[IMO]
FizzBuzz を変える、は少し意味が違いそうです。

「数字をFizzBuzzルールで文字列変換する」処理のようなので、
それがなにか別の形でも伝わると良いと思います。

2021-01-15 06:28 UTC, izumix03 commented on src/index.ts
> +export const outputFizzBuzz = ():Array< number | string > => {
[MUST]
> `Array< number | string >`

惜しいです。numberが入ることはありそうでしょうか？

2021-01-15 06:28 UTC, izumix03 commented on src/index.ts
> +export const resultFizzBuzz = ():string => {
[nits]
関数名は動詞が望ましいので、動詞で考えてみましょう！

2021-01-15 06:28 UTC, izumix03 commented on src/index.ts
> +  return  outputFizzBuzz().join(',')
👍

2021-01-15 06:38 UTC, izumix03 commented on README.md
> +#### 課題1-1
[nits]
課題としての記載になっていますが、
このプログラムでできることなので、 
FizzBuzz 問題とけるんだぜ！という内容にしてよいかと思います:star:

2021-01-15 06:38 UTC, izumix03 commented on README.md
> +### 環境設定
[IMO]
このリポジトリをcloneした後にするべきことを書くと良いです:star:
package.jsonに依存が保存されていると思うので、
下記の中に不要なコードたちがありそうですがいかがでしょうか？

2021-01-15 06:38 UTC, izumix03 commented on README.md
> +< yarn start >  コマンドを実行
・\`を3つの後、今回shellなのでshell 
・yarn start
・\`を3つ

みたいに書くのがコードスニペットの書き方になるのでぜひ使ってみて下さい！

2021-01-15 06:51 UTC, tsuruchan56 commented on .gitignore
> -# coverage
コメントの位置を間違えておりました...

PR時にはコメントインしていたのですが、pushされてしまったので、
> pushした coverage以下のファイルを取り消してみましょう！
こちら実行した後に再度試してみます！

2021-01-15 06:56 UTC, tsuruchan56 commented on src/index.ts
> +export const chengeFizzBuzz = (number: number): string => {
日本語：fizzbuzzへ文字列変換する → 英語：Convert string to fizzbuzz

convertStringFizzBuzz に変更します！

2021-01-15 06:56 UTC, tsuruchan56 commented on src/index.ts
> +export const outputFizzBuzz = ():Array< number | string > => {
stringのみです...！

修正しました！

2021-01-15 07:06 UTC, izumix03 commented on src/index.ts
> +export const chengeFizzBuzz = (number: number): string => {
それだと
文字列をfizzbuzzに変換する
なので、違うかもです💦

convertくらいでどうでしょう？！

2021-01-15 07:09 UTC, tsuruchan56 commented on src/index.ts
> +export const chengeFizzBuzz = (number: number): string => {
あ、確かに...💦

convertにします🙇‍♂️

2021-01-15 09:52 UTC, tsuruchan56 commented on README.md
> +### 環境設定
> % npm init -y
> % npx tsc --init  --outDir .dist --esModuleInterop --module commonjs


上記2つが不要だと考えましたがいかがでしょうか？👀

2021-01-18 05:18 UTC, kenta-isohata commented on .gitignore
> -# coverage
[ 🎉 ]
`coverage/` 以下がcommitされなくなりましたね！すばらCです〜〜〜  

こういう風に、プログラムの起動やメンテナンスに不要なファイルはcommitしないように設定しておくのが吉です。  
特に複数の人間が同じリポジトリを触る時（業務ではほとんどそう）、
誰かのlocalで`npm i`した`node_modules/`やmacのキャッシュファイルが紛れていたら、「なんやこれ」ってなるのは必至ですし、それが原因でなんかうまく動かへんなあみたいな事も起こりえます。

2021-01-18 05:19 UTC, kenta-isohata commented on coverage/clover.xml
> +<coverage generated="1610607050382" clover="3.2.0">
[ 🎉 ]
自分で調べて解決する流れ、これからめちゃくちゃ重要になります！バリバリ検索してバリバリ翻訳してみてくださーい

2021-01-18 05:23 UTC, kenta-isohata commented on src/index.ts
> +export const chengeFizzBuzz = (number: number): string => {
[MUST]
`.dist/index.js`が以前のままな気がします。
こいつをcommitするなら、元のtsファイルを変更したとき一緒に変更してcommit しましょう〜〜〜〜（他の人が、どっちが正しいんや？って迷っちゃうかも）

2021-01-18 05:29 UTC, kenta-isohata commented on README.md
> +### 環境設定
[ 🎉 ]
そいつらは不要ですね！初期設定を行うコマンドなので〜

2021-01-18 05:33 UTC, kenta-isohata commented on README.md
> +### 環境設定
[IMO]
```
npm install typescript @types/node  --save-dev
npm install ts-node --save-dev
```
このコマンドって、`typescript`と`@types/node`と`ts-node`を、依存に追加していますよね。
となると、その結果はpackage.jsonに保存されるはずです（devDependencies）。

もし必要な依存がすべてpackage.jsonに記載されていたら、このリポジトリを初めてcloneした人がすべきことはなんでしょう？
（もうちょっと簡素になるんちゃう？ってことを言いたいです！）

2021-01-18 05:39 UTC, kenta-isohata commented on src/index.ts
> +export const insertcomma = ():string => {
[IMO]
関数の命名規則は会社やチームのコーディングルールで指定されますが、
このリポジトリにおいてはlowerCammelCaseで統一されているので、それに従いましょう〜〜〜〜

ref: 
https://qiita.com/terra_yucco/items/ec437c6005932fd73fb9#%E3%83%AD%E3%82%A6%E3%83%AF%E3%83%BC%E3%82%AD%E3%83%A3%E3%83%A1%E3%83%AB%E3%82%B1%E3%83%BC%E3%82%B9--lower-camel-case

2021-01-18 05:40 UTC, kenta-isohata commented
[nits]
**prettier**を導入すると、セミコロンのつけ忘れとかインデントの調整とか自動でやってくれるので便利ですよ！
本リポジトリにおいては必須じゃないですが、次の課題から導入してみてください〜〜〜〜

2021-01-18 05:49 UTC, tsuruchan56 commented on src/index.ts
> +export const chengeFizzBuzz = (number: number): string => {
編集後実行していなかったので、トランスパイルできていませんでした...💦
必ず確認するようにします！！

2021-01-18 06:16 UTC, tsuruchan56 commented on README.md
> +### 環境設定
ありがとうございます！コマンドの認識が曖昧でしたっ！

> このコマンドって、typescriptと@types/nodeとts-nodeを、依存に追加していますよね。
> となると、その結果はpackage.jsonに保存されるはずです（devDependencies）。

となると、`jest @types/jest ts-jest -D `こちらも必要ないですね...！
`npm install`のみで良いかなと判断しました。

2021-01-18 06:33 UTC, tsuruchan56 commented on package.json
> +    "start": "ts-node src/index.ts.",
いろいろ試した中で、結局`ts-node`使っていないんでした...笑
今回変更してみました！

jsファイルは一応残しておりますっ

2021-01-18 06:42 UTC, kenta-isohata commented on README.md
> +### 環境設定
[ 🎉 ]
いいですね〜
package.jsonに依存を記載していれば、必要なモジュールを一つずつinstallする必要はありませんでしたね！

[MUST] 
`@types/node`って依存に追加されていますか？
このままだとinstallされない気がします！

2021-01-18 06:48 UTC, kenta-isohata commented on package.json
> +    "start": "ts-node src/index.ts.",
[ 🎉 ]
いろいろ試すの、とてもグッドです！
モジュールやフレームワークの選択肢が複数ある場合に、どれを使うべきか？に答えはないので、
そのとき適したものを検討して使うことになります。
そのためにいろいろ探してつかってみる経験を積むのはとてもいいですね〜〜〜〜

2021-01-18 07:07 UTC, tsuruchan56 commented on README.md
> +### 環境設定
追加できていませんでした💦
追加しました！！

2021-01-18 08:46 UTC, kenta-isohata commented on src/index.ts
> +export const convertFizzBuzzRules = (number: number): string => {
[nits]
`convertFizzBuzzRules `だと、「FizzBuzzRulesをconvertするで」という意味になりまする。
なので、「FizzBuzzRulesに則ってconvertするで」みたいにしたほうが、このメソッドが何をするのかわかりやすくなると思います。
`convertNumberByFizzBuzzRules`とかですかね〜〜〜〜
命名は難しいのですが、「見て迷わない」ことを第一に考えたいです。

2021-01-18 08:51 UTC, kenta-isohata commented on src/index.ts
> +export const insertComma = ():string => {
[nits]
微妙に、このメソッドがやっていることと関数名がずれている気がします。
これだけ見た人は、「何にカンマを挿入するんや？」「挿入しかやらないような名前なのに、内部でなんか違うソッド呼び出しとる！」って思うかもしれません。

これまたいろいろな考え方はあるのですが、
**内部で何をするか、ではなく、使う側にとって何をしてくれるかわかる関数名**にしたほうがわかりやすいと思っています。
上記の例で言えば、カンマを挿入するのは手段であって、使う側からは関係ないですね。
なので、`buildFizzBuzzString`みたいな名前にしてあげたほうが、「こいつはFizzBuzzの文字列をつくるんやなあ」と素直に感じられるかと思います。

2021-01-18 08:54 UTC, kenta-isohata commented on src/index.ts
> +export const insertComma = ():string => {
[nits]
↑つづきです

このまま`insertComma`とする場合、
カンマを入れる処理なのはわかるのですが、なんのどこにカンマ入れるか不明なので、それを引数で渡せるようにしてあげるとグッドかもです。

```typescript
export const insertComma = (joinTargetNumbers: Array<number>):string => { // これが最善とは限らないです
  // 処理
}

2021-01-18 09:24 UTC, merged